import { HeroPage } from '@components'
import { Header } from '@components'
import {HomePage} from '@components'
import { Layout } from '@layout'
import Head from 'next/head'
const Home = () => {
  return (
    < >
      <Head>
        <title>aubin ishimwe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <HomePage/>
    </>
  )
}

export default Home

