import { Header } from '@components'
import { Box, useTheme } from '@mui/material'
import Head from 'next/head'
import { Layout } from '@layout'
import { Hero } from '@components'
import AboutMe from '@components/AboutMe'
import ContactMe from '@components/ContactMe'
import Projects from '@components/Projects'

const Home = () => {
 const theme = useTheme()
 return (
  <>
   <Head>
    <title>aubin ishimwe</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/aubin.jpeg" />
   </Head>
   <Box
    sx={{
     bgcolor: `${theme?.palette?.background?.default}`,
     fontFamily: 'monospace',
    }}
   >
    <Header />
    <Layout>
     <Hero />
     <AboutMe />
     <Projects />
     <ContactMe />
    </Layout>
   </Box>
  </>
 )
}

export default Home
