import { Header } from '@components'
import { Hero } from '@components'
import AboutMe from '@components/AboutMe'
import ContactMe from '@components/ContactMe'
import { Layout } from '@layout'
import { Box, useTheme } from '@mui/material'
import Head from 'next/head'
const Home = () => {
  const theme=useTheme()
 return (
  <>
   <Head>
    <title>aubin ishimwe</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/aubin.jpeg" />
   </Head>
   {/* <HomePage/> */}
   <Box sx={{bgcolor:`${theme?.palette?.background?.default}`,fontFamily:"monospace"}}>
   <Header />
   <Layout>
    <Hero />
    <AboutMe/>
    <ContactMe/>
   </Layout>
   </Box>
  </>
 )
}

export default Home
